id: I444FBB56
legacy_id: P010727
ocr_import_info:
  bdrc_scan_id: W1CZ2547
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T17:09:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:24:43.093093+00:00'
last_modified: 2022-08-31 03:25:41.200791
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ2547
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ2547
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། རྒྱལ་སྲས་འགྱུར་མེད་རྡོ་རྗེ།
  author: ཨ་འཛོམ་རྒྱལ་སྲས་འགྱུར་མེད་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.5958163224103986
  ocr_word_median_confidence_index: 0.6399999856948853
quality: null
bases:
  I1CZ2722:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2722
      total_pages: 392
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2722.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6011877050934508
    legacy_id: v001
  I1CZ2723:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2723
      total_pages: 284
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1CZ2723.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5891536265096715
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
