id: I444FBB56
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T17:11:55+00:00'
last_modified: '2022-06-08T17:05:32.368670+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2547
  title: གསུང་ཐོར་བུ།  རྒྱལ་སྲས་འགྱུར་མེད་རྡོ་རྗེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A345:
      image_group_id: I1CZ2722
      title: ''
      total_pages: 392
      order: 1
      base_file: A345.txt
    CC4B:
      image_group_id: I1CZ2723
      title: ''
      total_pages: 284
      order: 2
      base_file: CC4B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
